name: Auto-fix Python Repository
on:
  push:
    branches:
      - main

jobs:
  python-auto-fix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort autoflake

    - name: Auto-fix code
      run: |
        black --exclude=venv .
        isort --skip-glob='**/venv/**' .
        autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "syntex"
        git push
