name: Auto Fix
on: [push]
jobs:
  python-auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort autoflake
      - name: Auto Fix
        run: |
          black --exclude=venv .
          isort --skip-glob='**/venv/**' .
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
      - name: Code Reformate
        uses: stefanzweifel/git-auto-commit-action@v4
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "`Automatic Correction`"
          git push
